[package]
name = "Baker"
version = "0.1.0"
authors = ["Germain Clavier <germain.clavier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

image = '*'
clap = '*'
rand = '*'
